name: deploy
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build  --tag ghcr.io/benjohnson/feedbin-news-truncator:latest .

      - name: Docker push
        run: docker push ghcr.io/benjohnson/feedbin-news-truncator:latest
